### ISSUE TITLE
Cannot get value of "host" to stick in configuration ui

### ISSUE THREAD

**Issue by andyfore** [davide125/hassio-addons#1]
In the configuration tab of the UI nothing I put in the field in place of "disabled" sticks after the change is saved and the add-on is restarted.  I have tried the IP of the host and the actual short hostname of the homeassistant  host.

Any ideas here?  Exactly what does this setting do?

**Comment by davide125** [comment]
That field should be the port you want to map from the container to the host. So, if you put 8581 there you should then be able to access the add-on from http://homeassistanthost:8581

**Comment by davide125** [comment]
Please reopen if this is still an issue
