### ISSUE TITLE
Homebridge reinstalling itself every restart!

### ISSUE THREAD

**Issue by VCTGomes** [davide125/hassio-addons#9]
Hi guys! I'm loving the Add-on. I have devices that works much better on Homebridge, with a simple interface and more trustable than HASS.

However I don't know the reason every restart is making my Homebridge reinstall itself! Even new updates from Node and home bridge UI back to the original! Plugins continue installed and working (Installing and Uninstalling new plugins aren't working as well).

I tried to remove and reinstall the Homebridge add-on, but it looks like my Settings continue saved, than it return with the same options and problems.

I have no ability with developer, than I need help.

`
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service tzupdate: starting
s6-rc: info: service setup: starting
s6-rc: info: service credits: starting
s6-rc: info: service banner: starting
    Thank you for using the oznu/homebridge docker image!
  If you find this project useful please STAR it on GitHub:
         https://github.com/oznu/docker-homebridge
                Or donate to the project:
            https://github.com/sponsors/oznu
                  https://paypal.me/oznu
s6-rc: info: service credits successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service tzupdate successfully started
s6-rc: info: service legacy-cont-init successfully started
-----------------------------------------------------------
 Add-on: Homebridge
 Lightweight HomeKit API implementation with plugin support
-----------------------------------------------------------
 Add-on version: 0.1.7
 You are running the latest version of this add-on.
Installing Homebridge and user plugins, please wait...
 System: Home Assistant OS 10.1  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2023.5.4
 Home Assistant Supervisor: 2023.04.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service banner successfully started
`

It continues crashed on this log until the new home bridge is installed, than it turns on!

**Comment by davide125** [comment]
This is tracked in #10.
